---
title: "Tablas"
author: "Natally S. Vidal-Figueroa"
date: "2025-09-25"
output: html_document
---

force=True obliga a instalar el paquete

```{r, message=FALSE}
library(gaawr2)
library(dplyr)
library(kableExtra)
library(knitr)
library(gt)
```

```{r}
data(diabetes)
head(diabetes)
```

```{r}
kable(head(diabetes,5), booktabs= TRUE) %>% 
  kable_styling(font_size = 12)

```
#??kable_styling

```{r}
kable(head(diabetes,5), booktabs= TRUE) %>% 
  kable_styling(font_size = 14, bootstrap_options = "striped",full_width = F)
```

```{r}
kable(head(diabetes[1:2],5), booktabs= TRUE) %>% 
  kable_styling(font_size = 14, bootstrap_options = "striped",full_width = F)
```

```{r}
kable(head(diabetes[,4:5]), booktabs= TRUE) %>% 
  kable_styling(font_size = 12, position = "left", bootstrap_options = "striped",full_width = F)
```

```{r}
#kable(head(diabetes,5), booktabs= TRUE) %>% 
 # kable_styling (bootstrap_options = "striped",full_width = F) %>% 
 # add_header_above(c("personal data"=4,"blood profile"=9,"weight"=1"))
```


```{r}
kable(diabetes,digits = 2,format = "html", row.names = TRUE) %>% 
  kable_styling(bootstrap_options = c("striped"), 
                full_width = T,
                font_size = 15) %>% 
  scroll_box(height = "300px")
```

